name: Build and Deploy Package

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Build with dotnet
        run: dotnet build WebSystem.Core/WebSystem.Core.csproj --configuration Release

      - name: Create WebSystem Package
        run: dotnet pack WebSystem.Core/WebSystem.Core.csproj --configuration Release

      - name: Publish
        run: dotnet nuget push "WebSystem.Core\bin\Release\WebSystem.1.0.8.nupkg" -k ${{ secrets.NUGET_TOKEN }} -s https://api.nuget.org/v3/index.json --skip-duplicate
